spring:
  batch:
    job:
      #设置为 false -需要jobLaucher.run执行
      enabled: false
    jdbc:
      initialize-schema: always
  #    table-prefix: my-batch

  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/world?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8665